# Generated by Django 6.0.2 on 2026-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published_date_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
